### ISSUE TITLE
"Maximum retries exceeded for README stats" error

### ISSUE THREAD

**Issue by SapphoSys** [jy1263/jy1263#1]
I've noticed this error in your README while browsing your profile.

![image](https://user-images.githubusercontent.com/22654782/225941277-7641a226-c039-430f-84f8-9f5e67f0a994.png)

**Comment by amydevs** [comment]
ty :3

**Comment by amydevs** [comment]
i think the person hosting the svg generator probably messed smth up and then fixed it
